### ISSUE TITLE
Code mis-formatted

### ISSUE THREAD

**Issue by PeteHanner** [learn-co-curriculum/programming-univbasics-2-repetition-while-variants#3]
The last code example under 

"Use Integer.times to Execute a Loop n-times"

is formatted as plan text.

**Comment by sgharms** [comment]
Gotcha. Change made.

**Comment by Giagnus64** [comment]
This issue is still present for me.

**Comment by Giagnus64** [comment]
![snip mistake](https://user-images.githubusercontent.com/28762593/59163199-b9b2ae80-8acb-11e9-8478-22ab65f2c722.png)

**Comment by sgharms** [comment]
@Giagnus64

I think this is a different issue as you're referring to a different bloc of code. I'll fix your issue, but generally, it's best to open new issues versus commenting on closed ones. Thanks.

Steven

**Comment by Giagnus64** [comment]
My mistake! Thanks for fixing it!
